# Generated by Django 2.2.2 on 2019-11-28 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=100)),
                ('link_url', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='banners/')),
                ('size', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('position_1', models.IntegerField(default=0)),
                ('position_2', models.IntegerField(default=0)),
                ('click_number', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
