# Generated by Django 2.2.2 on 2020-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
