# Generated by Django 2.2.2 on 2019-12-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='show_ad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='banners.Banner'),
        ),
    ]
