# Generated by Django 2.2.2 on 2019-12-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_notice_show_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercenter',
            old_name='url_link',
            new_name='secrete',
        ),
        migrations.RemoveField(
            model_name='customercenter',
            name='tag',
        ),
    ]
