# Generated by Django 2.2.2 on 2019-12-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20191220_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercenter',
            name='secrete',
        ),
        migrations.AddField(
            model_name='customercenter',
            name='secret',
            field=models.CharField(default='비공개', max_length=200),
        ),
    ]
