# Generated by Django 2.2.2 on 2019-12-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_auto_20191221_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercenter',
            name='secret',
            field=models.CharField(default='공개', max_length=200),
        ),
    ]
