# Generated by Django 2.2.2 on 2019-12-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_auto_20191221_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
