# Generated by Django 2.2.2 on 2019-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_auto_20191221_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercenter',
            name='secret',
            field=models.BooleanField(default='True'),
        ),
    ]
