# Generated by Django 2.2.2 on 2019-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_auto_20191221_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercenter',
            name='secret',
            field=models.CharField(default='True', max_length=200),
        ),
    ]
