# Generated by Django 2.2.2 on 2019-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_auto_20191221_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercenter',
            name='secret',
            field=models.BooleanField(default=True),
        ),
    ]
