# Generated by Django 2.2.2 on 2019-12-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_auto_20191221_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercenter',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
