# Generated by Django 2.2.2 on 2020-01-15 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20191221_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='comments',
            new_name='p_price_max',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='numstar',
            new_name='p_price_min',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='attribute',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='is_imaged',
            new_name='workday_fri',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='avgstar',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='g_map4',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='g_map5',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='present_image',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='show_ad',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='tag',
        ),
        migrations.AddField(
            model_name='promotion',
            name='address',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='brand_name',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img1',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img10',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img11',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img12',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img13',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img14',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img15',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img16',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img17',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img18',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img19',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img2',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img20',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img3',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img4',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img5',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img6',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img7',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img8',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_img9',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt1',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt10',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt11',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt12',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt13',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt14',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt15',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt16',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt17',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt18',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt19',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt2',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt20',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt3',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt4',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt5',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt6',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt7',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt8',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='opt9',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_img1',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_img2',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_img3',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_img4',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_img5',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_txt1',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_txt2',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_txt3',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_txt4',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rep_txt5',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_clean',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_kindness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_location',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_participate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_response',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='star_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='tag3',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='w_price_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='w_price_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workday_mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workday_sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workday_sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workday_thur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workday_tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workday_wed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='worktime_finish',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='worktime_start',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='board_kind',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='g_map1',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='g_map2',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='g_map3',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url_link',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
