# Generated by Django 2.2.2 on 2020-01-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20200115_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='board_kind',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='brand_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img16',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img17',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img18',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img19',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img20',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='detail_img9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='g_map1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='g_map2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='g_map3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt11',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt12',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt13',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt14',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt15',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt16',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt17',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt18',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt19',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt20',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='opt9',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_img1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_img2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_img3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_img4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_img5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_txt1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_txt2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_txt3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_txt4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rep_txt5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tag3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='worktime_finish',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='worktime_start',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
