# Generated by Django 2.2.2 on 2020-01-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20200115_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img1',
            new_name='pimg1',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img10',
            new_name='pimg10',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img11',
            new_name='pimg11',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img12',
            new_name='pimg12',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img13',
            new_name='pimg13',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img14',
            new_name='pimg14',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img15',
            new_name='pimg15',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img16',
            new_name='pimg16',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img17',
            new_name='pimg17',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img18',
            new_name='pimg18',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img19',
            new_name='pimg19',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img2',
            new_name='pimg2',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img20',
            new_name='pimg20',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img3',
            new_name='pimg3',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img4',
            new_name='pimg4',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img5',
            new_name='pimg5',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img6',
            new_name='pimg6',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img7',
            new_name='pimg7',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img8',
            new_name='pimg8',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='detail_img9',
            new_name='pimg9',
        ),
    ]
