# Generated by Django 2.2.2 on 2020-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20200115_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='icon',
            field=models.ImageField(blank=True, upload_to='promotions/opt_icon/'),
        ),
    ]
