# Generated by Django 2.2.2 on 2020-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_auto_20200116_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='sale_published',
            field=models.BooleanField(default=False),
        ),
    ]
