# Generated by Django 2.2.2 on 2020-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_promotion_sale_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='url_click',
            field=models.IntegerField(default=0),
        ),
    ]
