# Generated by Django 2.2.2 on 2020-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0011_auto_20200123_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
