# Generated by Django 2.2.2 on 2020-01-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_promotion_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='worktime_finish_weekend',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='worktime_start_weekend',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
