# Generated by Django 2.2.2 on 2020-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0014_auto_20200129_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='show_ad',
            field=models.CharField(default='여행사홍보', max_length=100),
        ),
    ]
