# Generated by Django 2.2.2 on 2020-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0016_auto_20200207_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
