# Generated by Django 2.2.2 on 2019-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20190617_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='position_2',
            field=models.IntegerField(default=0),
        ),
    ]
