# Generated by Django 2.2.2 on 2020-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20191220_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_gallery',
            name='star_clean',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_kindness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_location',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_response',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_gallery',
            name='star_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
