# Generated by Django 2.2.2 on 2020-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200124_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_clean',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_kindness',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_location',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_price',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_quality',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_response',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_service',
        ),
        migrations.RemoveField(
            model_name='comment_gallery',
            name='star_total',
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_clean',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_kindness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_location',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_response',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment_promotion',
            name='star_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
