# Generated by Django 2.2.2 on 2019-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboxs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgbox',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
    ]
