# Generated by Django 2.2.2 on 2019-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboxs', '0002_msgbox_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgbox',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
