# Generated by Django 2.2.2 on 2019-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboxs', '0003_auto_20191129_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm_addcommentlike',
            name='board_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
