# Generated by Django 2.2.2 on 2019-07-11 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_call', models.DateTimeField(default=datetime.datetime.now)),
                ('recall_min', models.IntegerField()),
                ('data_list', models.CharField(max_length=200)),
                ('data1', models.CharField(blank=True, max_length=100)),
                ('data2', models.CharField(blank=True, max_length=100)),
                ('data3', models.CharField(blank=True, max_length=100)),
                ('data4', models.CharField(blank=True, max_length=100)),
                ('data5', models.CharField(blank=True, max_length=100)),
                ('data6', models.CharField(blank=True, max_length=100)),
                ('data7', models.CharField(blank=True, max_length=100)),
                ('data8', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
