# Generated by Django 2.2.2 on 2019-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190618_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
