# Generated by Django 2.2.2 on 2019-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_schoolroulette'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolquiz',
            name='get_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolroulette',
            name='get_point',
            field=models.IntegerField(default=0),
        ),
    ]
