# Generated by Django 2.2.2 on 2020-01-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolQuiz',
        ),
        migrations.DeleteModel(
            name='SchoolRoulette',
        ),
    ]
