# Generated by Django 2.2.2 on 2020-01-13 12:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_auto_20200110_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main', models.ImageField(blank=True, upload_to='shoppings/')),
                ('main_size', models.CharField(default='826*321', max_length=100)),
                ('sub', models.ImageField(blank=True, upload_to='shoppings/')),
                ('sub_size', models.CharField(default='543*96', max_length=100)),
                ('link_url', models.CharField(max_length=200)),
                ('click_number', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.CharField(default='NONE', max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('url_link', models.CharField(blank=True, max_length=200)),
                ('click_number', models.IntegerField(default=0)),
                ('best_published', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
