# Generated by Django 2.2.2 on 2020-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200113_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_main',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
